@host = https://localhost:7267

@adminId=00000000-0000-0000-0000-000000000001

POST {{host}}/Subscriptions
Content-Type: application/json

{
  "SubscriptionType":"Free",
  "SubscriptionId": "{{adminId}}"
}